name: Dev CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up env
        env:
          ENV_DEV_PROPERTIES: ${{ secrets.ENV_DEV_PROPERTIES }}
          ROOT_KEYSTORE_DEV: ${{ secrets.ROOT_KEYSTORE_DEV }}
          ENV_PROD_PROPERTIES: ${{ secrets.ENV_PROD_PROPERTIES }}
          ROOT_KEYSTORE_PROD: ${{ secrets.ROOT_KEYSTORE_PROD }}
        run: |
          echo -n ${ENV_DEV_PROPERTIES} | base64 -d > env.dev.properties
          echo -n ${ROOT_KEYSTORE_DEV} | base64 -d > root-keystore-dev.jks
          echo -n ${ENV_PROD_PROPERTIES} | base64 -d > env.prod.properties
          echo -n ${ROOT_KEYSTORE_PROD} | base64 -d > root-keystore-prod.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew app:build

      - name: Build Release apk
        run: ./gradlew app:assembleDevRelease

      - name: Build Release bundle
        run: ./gradlew app:bundleDevRelease

      - name: Get release file aab path
        id: releaseAab
        run: echo "aabfile=$(find app/build/outputs/bundle/dev/release/*.aab)" >> $GITHUB_OUTPUT

      - name: Get release file apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/dev/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Zip Files
        uses: papeloto/action-zip@v1
        with:
          files: ${{ steps.releaseAab.outputs.aabfile }} ${{ steps.releaseApk.outputs.apkfile }}
          dest: app-dev-release.zip

      - name: Sending release build to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: app-dev-release.zip
          message: ğŸš€ New Release Published on DEV! >>> ${{github.head_ref}}.